<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="NODE319" name="Test" tests="5" failures="1" timestamp="14 Nov 2014 09:50:31 GMT" time="0.31" errors="0">
  <testcase name="happen" time="0.01" classname="com.sharepoint.TestNGtest.Annotations">
    <failure type="java.lang.IllegalArgumentException">
      <![CDATA[java.lang.IllegalArgumentException
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 10 stack frames]]>
    </failure>
  </testcase> <!-- happen -->
  <testcase name="happen" time="0.0" classname="com.sharepoint.TestNGtest.Annotations"/>
  <testcase name="happen" time="0.01" classname="com.sharepoint.TestNGtest.Annotations"/>
  <testcase name="happen" time="0.0" classname="com.sharepoint.TestNGtest.Annotations"/>
  <testcase name="happen" time="0.0" classname="com.sharepoint.TestNGtest.Annotations"/>
</testsuite> <!-- Test -->
